package hibernate;
// Generated May 25, 2020 11:55:22 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Brand generated by hbm2java
 */
public class Brand  implements java.io.Serializable {


     private Integer id;
     private String brandId;
     private String brand;
     private String description;
     private Set brandHasCategories = new HashSet(0);

    public Brand() {
    }

    public Brand(String brandId, String brand, String description, Set brandHasCategories) {
       this.brandId = brandId;
       this.brand = brand;
       this.description = description;
       this.brandHasCategories = brandHasCategories;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getBrandId() {
        return this.brandId;
    }
    
    public void setBrandId(String brandId) {
        this.brandId = brandId;
    }
    public String getBrand() {
        return this.brand;
    }
    
    public void setBrand(String brand) {
        this.brand = brand;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getBrandHasCategories() {
        return this.brandHasCategories;
    }
    
    public void setBrandHasCategories(Set brandHasCategories) {
        this.brandHasCategories = brandHasCategories;
    }




}


