package hibernate;
// Generated May 25, 2020 11:55:22 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * BrandHasCategory generated by hbm2java
 */
public class BrandHasCategory  implements java.io.Serializable {


     private Integer id;
     private Brand brand;
     private Category category;
     private Set products = new HashSet(0);

    public BrandHasCategory() {
    }

	
    public BrandHasCategory(Brand brand, Category category) {
        this.brand = brand;
        this.category = category;
    }
    public BrandHasCategory(Brand brand, Category category, Set products) {
       this.brand = brand;
       this.category = category;
       this.products = products;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Brand getBrand() {
        return this.brand;
    }
    
    public void setBrand(Brand brand) {
        this.brand = brand;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    public Set getProducts() {
        return this.products;
    }
    
    public void setProducts(Set products) {
        this.products = products;
    }




}


