package hibernate;
// Generated May 25, 2020 11:55:22 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category  implements java.io.Serializable {


     private Integer id;
     private ShopCategory shopCategory;
     private String categoryId;
     private String category;
     private String description;
     private Set brandHasCategories = new HashSet(0);

    public Category() {
    }

	
    public Category(ShopCategory shopCategory) {
        this.shopCategory = shopCategory;
    }
    public Category(ShopCategory shopCategory, String categoryId, String category, String description, Set brandHasCategories) {
       this.shopCategory = shopCategory;
       this.categoryId = categoryId;
       this.category = category;
       this.description = description;
       this.brandHasCategories = brandHasCategories;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public ShopCategory getShopCategory() {
        return this.shopCategory;
    }
    
    public void setShopCategory(ShopCategory shopCategory) {
        this.shopCategory = shopCategory;
    }
    public String getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId;
    }
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getBrandHasCategories() {
        return this.brandHasCategories;
    }
    
    public void setBrandHasCategories(Set brandHasCategories) {
        this.brandHasCategories = brandHasCategories;
    }




}


