package hibernate;
// Generated May 25, 2020 11:55:22 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer  implements java.io.Serializable {


     private Integer id;
     private String email;
     private String fname;
     private String lname;
     private Integer mobile;
     private String password;
     private Double rating;
     private String cusImg;
     private Set wishlists = new HashSet(0);
     private Set invoices = new HashSet(0);
     private Set carts = new HashSet(0);

    public Customer() {
    }

    public Customer(String email, String fname, String lname, Integer mobile, String password, Double rating, String cusImg, Set wishlists, Set invoices, Set carts) {
       this.email = email;
       this.fname = fname;
       this.lname = lname;
       this.mobile = mobile;
       this.password = password;
       this.rating = rating;
       this.cusImg = cusImg;
       this.wishlists = wishlists;
       this.invoices = invoices;
       this.carts = carts;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    public Integer getMobile() {
        return this.mobile;
    }
    
    public void setMobile(Integer mobile) {
        this.mobile = mobile;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Double getRating() {
        return this.rating;
    }
    
    public void setRating(Double rating) {
        this.rating = rating;
    }
    public String getCusImg() {
        return this.cusImg;
    }
    
    public void setCusImg(String cusImg) {
        this.cusImg = cusImg;
    }
    public Set getWishlists() {
        return this.wishlists;
    }
    
    public void setWishlists(Set wishlists) {
        this.wishlists = wishlists;
    }
    public Set getInvoices() {
        return this.invoices;
    }
    
    public void setInvoices(Set invoices) {
        this.invoices = invoices;
    }
    public Set getCarts() {
        return this.carts;
    }
    
    public void setCarts(Set carts) {
        this.carts = carts;
    }




}


