package hibernate;
// Generated May 25, 2020 11:55:22 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * DeliveryNote generated by hbm2java
 */
public class DeliveryNote  implements java.io.Serializable {


     private Integer id;
     private Delivery delivery;
     private Invoice invoice;
     private Date datetime;

    public DeliveryNote() {
    }

	
    public DeliveryNote(Delivery delivery, Invoice invoice) {
        this.delivery = delivery;
        this.invoice = invoice;
    }
    public DeliveryNote(Delivery delivery, Invoice invoice, Date datetime) {
       this.delivery = delivery;
       this.invoice = invoice;
       this.datetime = datetime;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Delivery getDelivery() {
        return this.delivery;
    }
    
    public void setDelivery(Delivery delivery) {
        this.delivery = delivery;
    }
    public Invoice getInvoice() {
        return this.invoice;
    }
    
    public void setInvoice(Invoice invoice) {
        this.invoice = invoice;
    }
    public Date getDatetime() {
        return this.datetime;
    }
    
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }




}


