package hibernate;
// Generated May 25, 2020 11:55:22 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Delivery generated by hbm2java
 */
public class Delivery  implements java.io.Serializable {


     private Integer id;
     private String nic;
     private String fname;
     private String lname;
     private Date dob;
     private Integer mobile;
     private String no;
     private String street;
     private String city;
     private String email;
     private String deliImg;
     private String birthDoc;
     private String gsDoc;
     private Double rating;
     private Set deliveryNotes = new HashSet(0);
     private Set returnGoods = new HashSet(0);

    public Delivery() {
    }

    public Delivery(String nic, String fname, String lname, Date dob, Integer mobile, String no, String street, String city, String email, String deliImg, String birthDoc, String gsDoc, Double rating, Set deliveryNotes, Set returnGoods) {
       this.nic = nic;
       this.fname = fname;
       this.lname = lname;
       this.dob = dob;
       this.mobile = mobile;
       this.no = no;
       this.street = street;
       this.city = city;
       this.email = email;
       this.deliImg = deliImg;
       this.birthDoc = birthDoc;
       this.gsDoc = gsDoc;
       this.rating = rating;
       this.deliveryNotes = deliveryNotes;
       this.returnGoods = returnGoods;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNic() {
        return this.nic;
    }
    
    public void setNic(String nic) {
        this.nic = nic;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }
    public Integer getMobile() {
        return this.mobile;
    }
    
    public void setMobile(Integer mobile) {
        this.mobile = mobile;
    }
    public String getNo() {
        return this.no;
    }
    
    public void setNo(String no) {
        this.no = no;
    }
    public String getStreet() {
        return this.street;
    }
    
    public void setStreet(String street) {
        this.street = street;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getDeliImg() {
        return this.deliImg;
    }
    
    public void setDeliImg(String deliImg) {
        this.deliImg = deliImg;
    }
    public String getBirthDoc() {
        return this.birthDoc;
    }
    
    public void setBirthDoc(String birthDoc) {
        this.birthDoc = birthDoc;
    }
    public String getGsDoc() {
        return this.gsDoc;
    }
    
    public void setGsDoc(String gsDoc) {
        this.gsDoc = gsDoc;
    }
    public Double getRating() {
        return this.rating;
    }
    
    public void setRating(Double rating) {
        this.rating = rating;
    }
    public Set getDeliveryNotes() {
        return this.deliveryNotes;
    }
    
    public void setDeliveryNotes(Set deliveryNotes) {
        this.deliveryNotes = deliveryNotes;
    }
    public Set getReturnGoods() {
        return this.returnGoods;
    }
    
    public void setReturnGoods(Set returnGoods) {
        this.returnGoods = returnGoods;
    }




}


