package hibernate;
// Generated May 25, 2020 11:55:22 AM by Hibernate Tools 4.3.1



/**
 * InvoiceItem generated by hbm2java
 */
public class InvoiceItem  implements java.io.Serializable {


     private Integer id;
     private Invoice invoice;
     private ShopHasProduct shopHasProduct;
     private Double qty;
     private Double unitprice;
     private Double total;

    public InvoiceItem() {
    }

	
    public InvoiceItem(Invoice invoice, ShopHasProduct shopHasProduct) {
        this.invoice = invoice;
        this.shopHasProduct = shopHasProduct;
    }
    public InvoiceItem(Invoice invoice, ShopHasProduct shopHasProduct, Double qty, Double unitprice, Double total) {
       this.invoice = invoice;
       this.shopHasProduct = shopHasProduct;
       this.qty = qty;
       this.unitprice = unitprice;
       this.total = total;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Invoice getInvoice() {
        return this.invoice;
    }
    
    public void setInvoice(Invoice invoice) {
        this.invoice = invoice;
    }
    public ShopHasProduct getShopHasProduct() {
        return this.shopHasProduct;
    }
    
    public void setShopHasProduct(ShopHasProduct shopHasProduct) {
        this.shopHasProduct = shopHasProduct;
    }
    public Double getQty() {
        return this.qty;
    }
    
    public void setQty(Double qty) {
        this.qty = qty;
    }
    public Double getUnitprice() {
        return this.unitprice;
    }
    
    public void setUnitprice(Double unitprice) {
        this.unitprice = unitprice;
    }
    public Double getTotal() {
        return this.total;
    }
    
    public void setTotal(Double total) {
        this.total = total;
    }




}


