package hibernate;
// Generated May 25, 2020 11:55:22 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private Integer id;
     private BrandHasCategory brandHasCategory;
     private String productId;
     private String proName;
     private String description;
     private Double rating;
     private Set shopHasProducts = new HashSet(0);

    public Product() {
    }

	
    public Product(BrandHasCategory brandHasCategory) {
        this.brandHasCategory = brandHasCategory;
    }
    public Product(BrandHasCategory brandHasCategory, String productId, String proName, String description, Double rating, Set shopHasProducts) {
       this.brandHasCategory = brandHasCategory;
       this.productId = productId;
       this.proName = proName;
       this.description = description;
       this.rating = rating;
       this.shopHasProducts = shopHasProducts;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public BrandHasCategory getBrandHasCategory() {
        return this.brandHasCategory;
    }
    
    public void setBrandHasCategory(BrandHasCategory brandHasCategory) {
        this.brandHasCategory = brandHasCategory;
    }
    public String getProductId() {
        return this.productId;
    }
    
    public void setProductId(String productId) {
        this.productId = productId;
    }
    public String getProName() {
        return this.proName;
    }
    
    public void setProName(String proName) {
        this.proName = proName;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Double getRating() {
        return this.rating;
    }
    
    public void setRating(Double rating) {
        this.rating = rating;
    }
    public Set getShopHasProducts() {
        return this.shopHasProducts;
    }
    
    public void setShopHasProducts(Set shopHasProducts) {
        this.shopHasProducts = shopHasProducts;
    }




}


