package hibernate;
// Generated May 25, 2020 11:55:22 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ReturnGood generated by hbm2java
 */
public class ReturnGood  implements java.io.Serializable {


     private Integer id;
     private Delivery delivery;
     private String returnId;
     private Date datetime;
     private Double qty;
     private String description;

    public ReturnGood() {
    }

	
    public ReturnGood(Delivery delivery) {
        this.delivery = delivery;
    }
    public ReturnGood(Delivery delivery, String returnId, Date datetime, Double qty, String description) {
       this.delivery = delivery;
       this.returnId = returnId;
       this.datetime = datetime;
       this.qty = qty;
       this.description = description;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Delivery getDelivery() {
        return this.delivery;
    }
    
    public void setDelivery(Delivery delivery) {
        this.delivery = delivery;
    }
    public String getReturnId() {
        return this.returnId;
    }
    
    public void setReturnId(String returnId) {
        this.returnId = returnId;
    }
    public Date getDatetime() {
        return this.datetime;
    }
    
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }
    public Double getQty() {
        return this.qty;
    }
    
    public void setQty(Double qty) {
        this.qty = qty;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


