package hibernate;
// Generated May 25, 2020 11:55:22 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ShopHasProduct generated by hbm2java
 */
public class ShopHasProduct  implements java.io.Serializable {


     private Integer id;
     private Product product;
     private Shop shop;
     private Double qty;
     private Double unitprice;
     private String proImg;
     private Date datetime;
     private String description;
     private Double rating;
     private Set carts = new HashSet(0);
     private Set wishlists = new HashSet(0);
     private Set invoiceItems = new HashSet(0);

    public ShopHasProduct() {
    }

	
    public ShopHasProduct(Product product, Shop shop) {
        this.product = product;
        this.shop = shop;
    }
    public ShopHasProduct(Product product, Shop shop, Double qty, Double unitprice, String proImg, Date datetime, String description, Double rating, Set carts, Set wishlists, Set invoiceItems) {
       this.product = product;
       this.shop = shop;
       this.qty = qty;
       this.unitprice = unitprice;
       this.proImg = proImg;
       this.datetime = datetime;
       this.description = description;
       this.rating = rating;
       this.carts = carts;
       this.wishlists = wishlists;
       this.invoiceItems = invoiceItems;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public Shop getShop() {
        return this.shop;
    }
    
    public void setShop(Shop shop) {
        this.shop = shop;
    }
    public Double getQty() {
        return this.qty;
    }
    
    public void setQty(Double qty) {
        this.qty = qty;
    }
    public Double getUnitprice() {
        return this.unitprice;
    }
    
    public void setUnitprice(Double unitprice) {
        this.unitprice = unitprice;
    }
    public String getProImg() {
        return this.proImg;
    }
    
    public void setProImg(String proImg) {
        this.proImg = proImg;
    }
    public Date getDatetime() {
        return this.datetime;
    }
    
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Double getRating() {
        return this.rating;
    }
    
    public void setRating(Double rating) {
        this.rating = rating;
    }
    public Set getCarts() {
        return this.carts;
    }
    
    public void setCarts(Set carts) {
        this.carts = carts;
    }
    public Set getWishlists() {
        return this.wishlists;
    }
    
    public void setWishlists(Set wishlists) {
        this.wishlists = wishlists;
    }
    public Set getInvoiceItems() {
        return this.invoiceItems;
    }
    
    public void setInvoiceItems(Set invoiceItems) {
        this.invoiceItems = invoiceItems;
    }




}


