package hibernate;
// Generated May 25, 2020 11:55:22 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Shop generated by hbm2java
 */
public class Shop  implements java.io.Serializable {


     private Integer id;
     private ShopCategory shopCategory;
     private String shopId;
     private String name;
     private String description;
     private String no;
     private String street;
     private String city;
     private Integer tp;
     private String email;
     private Double rating;
     private String shopImg;
     private Set shopHasProducts = new HashSet(0);

    public Shop() {
    }

	
    public Shop(ShopCategory shopCategory) {
        this.shopCategory = shopCategory;
    }
    public Shop(ShopCategory shopCategory, String shopId, String name, String description, String no, String street, String city, Integer tp, String email, Double rating, String shopImg, Set shopHasProducts) {
       this.shopCategory = shopCategory;
       this.shopId = shopId;
       this.name = name;
       this.description = description;
       this.no = no;
       this.street = street;
       this.city = city;
       this.tp = tp;
       this.email = email;
       this.rating = rating;
       this.shopImg = shopImg;
       this.shopHasProducts = shopHasProducts;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public ShopCategory getShopCategory() {
        return this.shopCategory;
    }
    
    public void setShopCategory(ShopCategory shopCategory) {
        this.shopCategory = shopCategory;
    }
    public String getShopId() {
        return this.shopId;
    }
    
    public void setShopId(String shopId) {
        this.shopId = shopId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getNo() {
        return this.no;
    }
    
    public void setNo(String no) {
        this.no = no;
    }
    public String getStreet() {
        return this.street;
    }
    
    public void setStreet(String street) {
        this.street = street;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public Integer getTp() {
        return this.tp;
    }
    
    public void setTp(Integer tp) {
        this.tp = tp;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Double getRating() {
        return this.rating;
    }
    
    public void setRating(Double rating) {
        this.rating = rating;
    }
    public String getShopImg() {
        return this.shopImg;
    }
    
    public void setShopImg(String shopImg) {
        this.shopImg = shopImg;
    }
    public Set getShopHasProducts() {
        return this.shopHasProducts;
    }
    
    public void setShopHasProducts(Set shopHasProducts) {
        this.shopHasProducts = shopHasProducts;
    }




}


