package hibernate;
// Generated May 25, 2020 11:55:22 AM by Hibernate Tools 4.3.1



/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer id;
     private UserType userType;
     private String email;
     private String username;
     private String password;
     private String userImg;

    public User() {
    }

	
    public User(UserType userType) {
        this.userType = userType;
    }
    public User(UserType userType, String email, String username, String password, String userImg) {
       this.userType = userType;
       this.email = email;
       this.username = username;
       this.password = password;
       this.userImg = userImg;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public UserType getUserType() {
        return this.userType;
    }
    
    public void setUserType(UserType userType) {
        this.userType = userType;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getUserImg() {
        return this.userImg;
    }
    
    public void setUserImg(String userImg) {
        this.userImg = userImg;
    }




}


